package com.kurui.kums.finance.entity;

// Generated 2011-12-2 4:17:12 by Hibernate Tools 3.2.2.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.kurui.kums.finance.BudgetOrder;

/**
 * Budget generated by hbm2java
 */

public class _Budget extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected String no;
	protected String name;
	protected Timestamp beginTime;
	protected Timestamp endTime;
	protected String companyNo;
	protected String entryOperator;
	protected Long type;
	protected Long status;
	protected Set<BudgetOrder> budgetOrders = new HashSet<BudgetOrder>(0);

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNo() {

		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Timestamp getBeginTime() {

		return this.beginTime;
	}

	public void setBeginTime(Timestamp beginTime) {
		this.beginTime = beginTime;
	}

	public Timestamp getEndTime() {

		return this.endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	public String getCompanyNo() {

		return this.companyNo;
	}

	public void setCompanyNo(String companyNo) {
		this.companyNo = companyNo;
	}

	public String getEntryOperator() {

		return this.entryOperator;
	}

	public void setEntryOperator(String entryOperator) {
		this.entryOperator = entryOperator;
	}

	public Long getType() {

		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {

		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public Set<BudgetOrder> getBudgetOrders() {

		return this.budgetOrders;
	}

	public void setBudgetOrders(Set<BudgetOrder> budgetOrders) {
		this.budgetOrders = budgetOrders;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
