package com.kurui.kums.agent.entity;

// Generated 2011-10-13 13:31:03 by Hibernate Tools 3.2.2.GA

import java.sql.Timestamp;

import com.kurui.kums.agent.Agent;
import com.kurui.kums.agent.Coterie;

/**
 * AgentCoterie generated by hbm2java
 */

public class _AgentCoterie extends org.apache.struts.action.ActionForm
		implements Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected Agent subAgent;
	protected Coterie coterie;
	protected Timestamp createTime;
	protected Timestamp fromTime;
	protected Timestamp expireTime;
	protected Long status;

	public long getId() {

		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Agent getSubAgent() {
		return this.subAgent;
	}

	public void setSubAgent(Agent subAgent) {
		this.subAgent = subAgent;
	}

	public Coterie getCoterie() {
		return this.coterie;
	}

	public void setCoterie(Coterie coterie) {
		this.coterie = coterie;
	}

	public Timestamp getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getFromTime() {
		return fromTime;
	}

	public void setFromTime(Timestamp fromTime) {
		this.fromTime = fromTime;
	}

	public Timestamp getExpireTime() {
		return expireTime;
	}

	public void setExpireTime(Timestamp expireTime) {
		this.expireTime = expireTime;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
