package com.kurui.kums.agent.entity;

import java.sql.Timestamp; // Generated 2011-9-24 12:56:38 by Hibernate Tools 3.2.2.GA

import com.kurui.kums.agent.Agent;

/**
 * AgentRelation generated by hbm2java
 */

public class _AgentRelation extends org.apache.struts.action.ActionForm
		implements Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected Long relationType;
	protected Timestamp updateTime;
	protected Long status;
	protected String userNo;
	protected Agent rootAgent;
	protected Agent relateAgent;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getRelationType() {
		return relationType;
	}

	public void setRelationType(Long relationType) {
		this.relationType = relationType;
	}

	public Timestamp getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getUserNo() {
		return userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	public Agent getRootAgent() {
		return rootAgent;
	}

	public void setRootAgent(Agent rootAgent) {
		this.rootAgent = rootAgent;
	}

	public Agent getRelateAgent() {
		return relateAgent;
	}

	public void setRelateAgent(Agent relateAgent) {
		this.relateAgent = relateAgent;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
