package com.kurui.kums.agent.entity;

// Generated 2011-10-13 13:39:29 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import com.kurui.kums.agent.Agent;

/**
 * Coterie generated by hbm2java
 */

public class _Coterie extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected Agent rootAgent;
	protected String name;
	protected Long status;
	protected String memo;
	protected Set agentCoteries = new HashSet(0);

	public long getId() {

		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Agent getRootAgent() {
		return rootAgent;
	}

	public void setRootAgent(Agent rootAgent) {
		this.rootAgent = rootAgent;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getStatus() {

		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getMemo() {

		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getAgentCoteries() {

		return this.agentCoteries;
	}

	public void setAgentCoteries(Set agentCoteries) {
		this.agentCoteries = agentCoteries;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
