package com.kurui.kums.agent.entity;

// Generated 2011-9-28 14:46:04 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.kurui.kums.agent.Agent;

/**
 * DirectLevel generated by hbm2java
 */

public class _DirectLevel extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected String name;
	protected BigDecimal directDiscount;
	protected BigDecimal normalDiscount;
	protected BigDecimal directorDiscount;
	protected BigDecimal managerDiscount;
	protected BigDecimal adManagerDiscount;
	protected Long seqIndex;
	protected Long type;
	protected Long status;
	protected Set<Agent> agents = new HashSet<Agent>(0);

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getDirectDiscount() {
		if (directDiscount == null) {
			return BigDecimal.ZERO;
		}
		return directDiscount;
	}

	public void setDirectDiscount(BigDecimal directDiscount) {
		this.directDiscount = directDiscount;
	}

	public BigDecimal getNormalDiscount() {
		if (normalDiscount == null) {
			return BigDecimal.ZERO;
		}
		return normalDiscount;
	}

	public void setNormalDiscount(BigDecimal normalDiscount) {
		this.normalDiscount = normalDiscount;
	}

	public BigDecimal getDirectorDiscount() {
		if (directorDiscount == null) {
			return BigDecimal.ZERO;
		}
		return directorDiscount;
	}

	public void setDirectorDiscount(BigDecimal directorDiscount) {
		this.directorDiscount = directorDiscount;
	}

	public BigDecimal getManagerDiscount() {
		if (managerDiscount == null) {
			return BigDecimal.ZERO;
		}
		return managerDiscount;
	}

	public void setManagerDiscount(BigDecimal managerDiscount) {
		this.managerDiscount = managerDiscount;
	}

	public BigDecimal getAdManagerDiscount() {
		if (adManagerDiscount == null) {
			return BigDecimal.ZERO;
		}
		return adManagerDiscount;
	}

	public void setAdManagerDiscount(BigDecimal adManagerDiscount) {
		this.adManagerDiscount = adManagerDiscount;
	}

	public Long getSeqIndex() {
		return seqIndex;
	}

	public void setSeqIndex(Long seqIndex) {
		this.seqIndex = seqIndex;
	}

	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public Set<Agent> getAgents() {
		return this.agents;
	}

	public void setAgents(Set<Agent> agents) {
		this.agents = agents;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
