package com.kurui.kums.agent.entity;

// Generated 2011-10-26 2:32:50 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import com.kurui.kums.agent.Agent;
import com.kurui.kums.transaction.Company;

/**
 * ShareHolder generated by hbm2java
 */

public class _ShareHolder extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected Company company;
	protected Agent agent;
	protected BigDecimal capitalAmount;
	protected Long controlType;
	protected Long status;
	protected String memo;

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Company getCompany() {

		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Agent getAgent() {

		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	public BigDecimal getCapitalAmount() {
		if (capitalAmount == null) {
			return BigDecimal.ZERO;
		}
		return this.capitalAmount;
	}

	public void setCapitalAmount(BigDecimal capitalAmount) {
		this.capitalAmount = capitalAmount;
	}

	public Long getControlType() {
		return controlType;
	}

	public void setControlType(Long controlType) {
		this.controlType = controlType;
	}

	public Long getStatus() {

		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getMemo() {

		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
