package com.kurui.kums.market.entity;

// Generated 2011-11-11 18:36:25 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.kurui.kums.market.EstateDish;

/**
 * Apartment generated by hbm2java
 */

public class _Apartment extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected String no;
	protected EstateDish estateDish;
	protected String name;
	protected Long transactionType;
	protected Long businessType;
	protected String houseType;
	protected String area;
	protected String owner;
	protected String linkman;
	protected String connection;
	protected Timestamp snatchTime;
	protected BigDecimal quotePrice;
	protected BigDecimal averageAreaPrice;
	protected String memo;
	protected Long status;
	protected Long type;

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public EstateDish getEstateDish() {
		return this.estateDish;
	}

	public void setEstateDish(EstateDish estateDish) {
		this.estateDish = estateDish;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(Long transactionType) {
		this.transactionType = transactionType;
	}

	

	public Long getBusinessType() {
		return businessType;
	}

	public void setBusinessType(Long businessType) {
		this.businessType = businessType;
	}

	public String getHouseType() {

		return this.houseType;
	}

	public void setHouseType(String houseType) {
		this.houseType = houseType;
	}

	public String getArea() {

		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getOwner() {

		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getLinkman() {

		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getConnection() {
		return connection;
	}

	public void setConnection(String connection) {
		this.connection = connection;
	}

	public Timestamp getSnatchTime() {

		return this.snatchTime;
	}

	public void setSnatchTime(Timestamp snatchTime) {
		this.snatchTime = snatchTime;
	}

	public BigDecimal getQuotePrice() {
		if (quotePrice == null) {
			return BigDecimal.ZERO;
		}
		return this.quotePrice;
	}

	public void setQuotePrice(BigDecimal quotePrice) {
		this.quotePrice = quotePrice;
	}

	public BigDecimal getAverageAreaPrice() {
		if (averageAreaPrice == null) {
			return BigDecimal.ZERO;
		}
		return this.averageAreaPrice;
	}

	public void setAverageAreaPrice(BigDecimal averageAreaPrice) {
		this.averageAreaPrice = averageAreaPrice;
	}

	public String getMemo() {

		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getStatus() {

		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public Long getType() {

		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
