package com.kurui.kums.market.entity;

// Generated 2011-11-11 18:36:25 by Hibernate Tools 3.2.2.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.kurui.kums.market.Apartment;
import com.kurui.kums.transaction.Company;

/**
 * EstateDish generated by hbm2java
 */

public class _EstateDish extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected String no;
	protected Company company;
	protected String name;
	protected Timestamp beginTime;
	protected Timestamp entranceTime;
	protected String address;
	protected String memo;
	protected Long type;
	protected Long status;
	protected Set<Apartment> apartments = new HashSet<Apartment>(0);

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	

	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public Company getCompany() {

		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Timestamp getBeginTime() {

		return this.beginTime;
	}

	public void setBeginTime(Timestamp beginTime) {
		this.beginTime = beginTime;
	}
	
	public Timestamp getEntranceTime() {
		return entranceTime;
	}

	public void setEntranceTime(Timestamp entranceTime) {
		this.entranceTime = entranceTime;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getType() {

		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {

		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public Set<Apartment> getApartments() {

		return this.apartments;
	}

	public void setApartments(Set<Apartment> apartments) {
		this.apartments = apartments;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
