package com.kurui.kums.market.entity;

// Generated 2011-8-17 9:59:26 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;
import com.kurui.kums.market.PriceReference;
import com.kurui.kums.transaction.Company;

/**
 * PriceIndex generated by hbm2java
 */

public class _PriceIndex extends org.apache.struts.action.ActionForm implements
		Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected long id;
	protected PriceReference priceReference;
	protected Company gatherCompany;
	protected BigDecimal price;
	protected BigDecimal maxPrice;
	protected BigDecimal minPrice;
	protected BigDecimal range;
	protected Timestamp snatchTime;
	protected String entryOperator;
	protected String memo;
	protected Long status;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PriceReference getPriceReference() {
		return this.priceReference;
	}

	public void setPriceReference(PriceReference priceReference) {
		this.priceReference = priceReference;
	}

	public Company getGatherCompany() {
		return gatherCompany;
	}

	public void setGatherCompany(Company gatherCompany) {
		this.gatherCompany = gatherCompany;
	}

	public BigDecimal getPrice() {
		if(price==null){
			return BigDecimal.ZERO;
		}
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getMaxPrice() {
		if(maxPrice==null){
			return BigDecimal.ZERO;
		}
		return maxPrice;
	}

	public void setMaxPrice(BigDecimal maxPrice) {
		this.maxPrice = maxPrice;
	}

	public BigDecimal getMinPrice() {
		if(minPrice==null){
			return BigDecimal.ZERO;
		}
		return minPrice;
	}

	public void setMinPrice(BigDecimal minPrice) {
		this.minPrice = minPrice;
	}

	public BigDecimal getRange() {
		if(range==null){
			return BigDecimal.ZERO;
		}
		return range;
	}

	public void setRange(BigDecimal range) {
		this.range = range;
	}

	public Timestamp getSnatchTime() {
		return this.snatchTime;
	}

	public void setSnatchTime(Timestamp snatchTime) {
		this.snatchTime = snatchTime;
	}

	public String getEntryOperator() {
		return this.entryOperator;
	}

	public void setEntryOperator(String entryOperator) {
		this.entryOperator = entryOperator;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
