package com.kurui.kums.market.entity;


import java.util.HashSet;
import java.util.Set;
import com.kurui.kums.market.PriceIndex;

/**
 * PriceReference generated by hbm2java
 */

public class _PriceReference extends org.apache.struts.action.ActionForm
		implements Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected long id;
	protected String name;
	protected String code;
	protected String money;
	protected String unit;
	protected String memo;
	protected Long type;
	protected Long status;
	protected Set<PriceIndex> priceIndexes = new HashSet<PriceIndex>(0);

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getMoney() {
		return money;
	}

	public void setMoney(String money) {
		this.money = money;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public Set<PriceIndex> getPriceIndexes() {
		return this.priceIndexes;
	}

	public void setPriceIndexes(Set<PriceIndex> priceIndexes) {
		this.priceIndexes = priceIndexes;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
