package com.kurui.kums.market.entity;

// Generated 2011-9-29 4:06:41 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.kurui.kums.finance.OrderDetail;

/**
 * Product generated by hbm2java
 */

public class _Product extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected String no;
	protected String name;
	protected String productType;
	protected BigDecimal price;
	protected BigDecimal purchasePrice;
	protected BigDecimal tradePrice;
	protected Long classType;
	protected String standard;
	protected BigDecimal proportion;
	protected Long stockCount;
	protected String memo;
	protected Long type;
	protected Long status;
	protected Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	


	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	

	public String getProductType() {
		return productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public BigDecimal getPrice() {
		if(this.price==null){
			return BigDecimal.ZERO;
		}
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	
	

	public BigDecimal getPurchasePrice() {
		if(this.purchasePrice==null){
			return BigDecimal.ZERO;
		}
		return purchasePrice;
	}

	public void setPurchasePrice(BigDecimal purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	public BigDecimal getTradePrice() {
		if(this.tradePrice==null){
			return BigDecimal.ZERO;
		}
		return tradePrice;
	}

	public void setTradePrice(BigDecimal tradePrice) {
		this.tradePrice = tradePrice;
	}

	public Long getStockCount() {
		return stockCount;
	}

	public void setStockCount(Long stockCount) {
		this.stockCount = stockCount;
	}

	public Long getClassType() {
		return classType;
	}

	public void setClassType(Long classType) {
		this.classType = classType;
	}

	public String getStandard() {
		return this.standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	public BigDecimal getProportion() {
		if(this.proportion==null){
			return BigDecimal.ZERO;
		}
		return this.proportion;
	}

	public void setProportion(BigDecimal proportion) {
		this.proportion = proportion;
	}

	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}
	
	public Set<OrderDetail> getOrderDetails() {
		return orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	// end of extra code

}
