package com.kurui.kums.market;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import com.kurui.kums.base.Constant;
import com.kurui.kums.base.util.DateUtil;
import com.kurui.kums.market.entity._PriceIndex;

/**
 * PriceIndex generated by hbm2java
 */

public class PriceIndex extends _PriceIndex {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long priceReferenceId = Long.valueOf(0);
	private long gatherCompanyId = Long.valueOf(0);

	private String priceReferenceName = "";

	private Long[] priceIndexIds = new Long[0];
	private Long[] priceReferenceIds = new Long[0];
	private Long[] gatherCompanyIds = new Long[0];
	private BigDecimal[] prices = new BigDecimal[0];
	private BigDecimal[] maxPrices = new BigDecimal[0];
	private BigDecimal[] minPrices = new BigDecimal[0];
	private BigDecimal[] ranges = new BigDecimal[0];
	private Timestamp[] snatchTimes = new Timestamp[0];
	private String[] memos = new String[0];
	private Long[] statuss = new Long[0];

	// 类型
	public static final long type_1 = 1;// 买入平台
	public static final long type_2 = 2;// 卖出平台
	public static final long type_3 = 3;// 买卖平台

	// 状态
	public static final long STATES_1 = 1;// 有效
	public static final long STATES_0 = 0;// 无效

	public String getShowSnatchTime() {
		String mydate = "";
		if (this.snatchTime != null && "".equals(snatchTime) == false) {
			Date tempDate = new Date(snatchTime.getTime());
			mydate = DateUtil.getDateString(tempDate, "yyyy-MM-dd HH:mm:ss");
		}
		return mydate;
	}
	
	private String snatchDate = "";

	public String getSnatchDate() {
		if (this.snatchTime != null && "".equals(snatchTime) == false) {
			Date tempDate = new Date(snatchTime.getTime());
			snatchDate = DateUtil
					.getDateString(tempDate, "yyyy-MM-dd");
		}
		return snatchDate;
	}

	public void setSnatchDate(String snatchDate) {
		this.snatchDate = snatchDate;
	}

	// public String getTypeInfo() {
	// if (this.getType() != null) {
	// if (this.getType().intValue() == type_1) {
	// return "买入平台";
	// } else if (this.getType().intValue() == type_2) {
	// return "卖出平台";
	// } else if (this.getType().intValue() == type_3) {
	// return "买卖平台";
	// } else {
	// return "";
	// }
	// } else {
	// return "";
	// }
	// }

	// 状态
	public String getStatusInfo() {
		if (this.getStatus() != null) {
			if (this.getStatus() == STATES_1) {
				return "有效";
			} else if (this.getStatus().intValue() == STATES_0) {
				return "无效";
			} else {
				return null;
			}
		} else {
			return null;
		}
	}

	public String rangeHtml = "";

	public String getRangeHtml() {
		String html = "";
		range = Constant.toBigDecimal(this.range);
		if (range.compareTo(BigDecimal.ZERO) > 0) {
			html = "<span style=\"color:Red\">" + getRangeInfo() + "</span>";
		} else if (range.compareTo(BigDecimal.ZERO) < 0) {
			html = "<span style=\"color:Green\">" + getRangeInfo() + "</span>";
		} else {
			html = range + "";
		}
		return html;
	}

	public String rangeInfo = "";

	public String getRangeInfo() {
		if (range != null) {
			rangeInfo = Constant.toPercentByBigDecimal(range);
		}
		return rangeInfo;
	}

	public void setRangeInfo(String rangeInfo) {
		this.rangeInfo = rangeInfo;
	}

	public long getPriceReferenceId() {
		return priceReferenceId;
	}

	public void setPriceReferenceId(long priceReferenceId) {
		this.priceReferenceId = priceReferenceId;
	}

	public long getGatherCompanyId() {
		return gatherCompanyId;
	}

	public void setGatherCompanyId(long gatherCompanyId) {
		this.gatherCompanyId = gatherCompanyId;
	}

	public String getPriceReferenceName() {
		return priceReferenceName;
	}

	public void setPriceReferenceName(String priceReferenceName) {
		this.priceReferenceName = priceReferenceName;
	}

	public Long[] getPriceIndexIds() {
		return priceIndexIds;
	}

	public void setPriceIndexIds(Long[] priceIndexIds) {
		this.priceIndexIds = priceIndexIds;
	}

	public Long[] getPriceReferenceIds() {
		return priceReferenceIds;
	}

	public void setPriceReferenceIds(Long[] priceReferenceIds) {
		this.priceReferenceIds = priceReferenceIds;
	}

	public Long[] getGatherCompanyIds() {
		return gatherCompanyIds;
	}

	public void setGatherCompanyIds(Long[] gatherCompanyIds) {
		this.gatherCompanyIds = gatherCompanyIds;
	}

	public BigDecimal[] getPrices() {
		return prices;
	}

	public void setPrices(BigDecimal[] prices) {
		this.prices = prices;
	}

	public BigDecimal[] getMaxPrices() {
		return maxPrices;
	}

	public void setMaxPrices(BigDecimal[] maxPrices) {
		this.maxPrices = maxPrices;
	}

	public BigDecimal[] getMinPrices() {
		return minPrices;
	}

	public void setMinPrices(BigDecimal[] minPrices) {
		this.minPrices = minPrices;
	}

	public BigDecimal[] getRanges() {
		return ranges;
	}

	public void setRanges(BigDecimal[] ranges) {
		this.ranges = ranges;
	}

	public Timestamp[] getSnatchTimes() {
		return snatchTimes;
	}

	public void setSnatchTimes(Timestamp[] snatchTimes) {
		this.snatchTimes = snatchTimes;
	}

	public String[] getMemos() {
		return memos;
	}

	public void setMemos(String[] memos) {
		this.memos = memos;
	}

	public Long[] getStatuss() {
		return statuss;
	}

	public void setStatuss(Long[] statuss) {
		this.statuss = statuss;
	}

}
