package com.kurui.kums.transaction.entity;


/**
 * Account generated by hbm2java
 */

public class _Account

extends org.apache.struts.action.ActionForm implements Cloneable {
	private static final long serialVersionUID = 1L;

	// Fields

	protected long id;
	protected String name;
	protected String accountNo;
	protected String accountAddress;
	protected Long personalType;
	protected Long businessType;
	protected Long tranType;
	protected Long type;
	protected String description;
	protected Long status;
	protected java.util.Set financeOrders = new java.util.HashSet(0);
	protected com.kurui.kums.transaction.PaymentTool paymentTool;
	protected java.util.Set platComAccounts = new java.util.HashSet(0);
	protected java.util.Set accountChecks = new java.util.HashSet(0);
	protected java.util.Set agentAccounts = new java.util.HashSet(0);
	protected java.util.Set companyAccounts = new java.util.HashSet(0);

	// Property accessors



	// The following is extra code specified in the hbm.xml files

	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAccountNo() {
		return accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public String getAccountAddress() {
		return accountAddress;
	}

	public void setAccountAddress(String accountAddress) {
		this.accountAddress = accountAddress;
	}

	
	
	public Long getPersonalType() {
		return personalType;
	}

	public void setPersonalType(Long personalType) {
		this.personalType = personalType;
	}

	public Long getBusinessType() {
		return businessType;
	}

	public void setBusinessType(Long businessType) {
		this.businessType = businessType;
	}

	public Long getTranType() {
		return tranType;
	}

	public void setTranType(Long tranType) {
		this.tranType = tranType;
	}

	public Long getType() {
		return type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public java.util.Set getFinanceOrders() {
		return financeOrders;
	}

	public void setFinanceOrders(java.util.Set financeOrders) {
		this.financeOrders = financeOrders;
	}

	public com.kurui.kums.transaction.PaymentTool getPaymentTool() {
		return paymentTool;
	}

	public void setPaymentTool(com.kurui.kums.transaction.PaymentTool paymentTool) {
		this.paymentTool = paymentTool;
	}

	public java.util.Set getPlatComAccounts() {
		return platComAccounts;
	}

	public void setPlatComAccounts(java.util.Set platComAccounts) {
		this.platComAccounts = platComAccounts;
	}

	public java.util.Set getAccountChecks() {
		return accountChecks;
	}

	public void setAccountChecks(java.util.Set accountChecks) {
		this.accountChecks = accountChecks;
	}

	public java.util.Set getAgentAccounts() {
		return agentAccounts;
	}

	public void setAgentAccounts(java.util.Set agentAccounts) {
		this.agentAccounts = agentAccounts;
	}

	public java.util.Set getCompanyAccounts() {
		return companyAccounts;
	}

	public void setCompanyAccounts(java.util.Set companyAccounts) {
		this.companyAccounts = companyAccounts;
	}



	// end of extra code specified in the hbm.xml files

}
