package com.kurui.kums.system.entity;

import com.kurui.kums.system.OperateLogDetail;

/**
 * operateLog generated by hbm2java
 */

public class _OperateLog

extends org.apache.struts.action.ActionForm implements Cloneable {
	private static final long serialVersionUID = 1L;

	// Fields

	protected long id;
	protected Long orderId;
	protected Long orderType;
	protected java.sql.Timestamp optTime;
	protected Long type;
	protected Long status;
	protected com.kurui.kums.right.SysUser sysUser;
	protected OperateLogDetail operateLogDetail;

	// Constructors

	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Long getOrderType() {
		return this.orderType;
	}

	public void setOrderType(Long orderType) {
		this.orderType = orderType;
	}

	public java.sql.Timestamp getOptTime() {
		return this.optTime;
	}

	public void setOptTime(java.sql.Timestamp optTime) {
		this.optTime = optTime;
	}

	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public com.kurui.kums.right.SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(com.kurui.kums.right.SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public OperateLogDetail getOperateLogDetail() {
		return operateLogDetail;
	}

	public void setOperateLogDetail(OperateLogDetail operateLogDetail) {
		this.operateLogDetail = operateLogDetail;
	}

	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code specified in the hbm.xml files

}
